# Generated by Django 3.0.1 on 2019-12-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_name', models.CharField(max_length=50)),
                ('Memory', models.CharField(default='', max_length=50)),
                ('Processor', models.CharField(default='', max_length=50)),
                ('Camera', models.CharField(default='', max_length=100)),
                ('Messaging', models.CharField(default='', max_length=100)),
                ('category', models.CharField(max_length=300)),
                ('Other_features', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
